# odysseusai-searxng-profile-v2
use_default_settings:
  engines:
    remove:
      - ahmia
      - radio browser
      - torch
      - wikidata

server:
  limiter: false
  secret_key: "__SEARXNG_SECRET__"

search:
  formats:
    - html
    - json
